import { useState } from "react";
import { ArrowUpLeft, CalendarPlus, Check, ChevronLeft, Clock3, MoreHorizontal, PhoneCall, Plus, X } from "lucide-react";
import { Link } from "wouter";
import { usePreferences } from "@/lib/preferences";

type Appointment = { id: number; time: string; name: string; initials: string; service: string; doctor: string; status: "مؤكد" | "بانتظار التأكيد" | "وصل" | "ملغي"; tone: string };
const appointments: Appointment[] = [
  { id: 1, time: "٠٩:٠٠", name: "سارة عبدالعزيز", initials: "سع", service: "استشارة جلدية", doctor: "د. نورة الحربي", status: "وصل", tone: "bg-[#d9f0e8] text-[#176b58]" },
  { id: 2, time: "٠٩:٣٠", name: "محمد العتيبي", initials: "مع", service: "تنظيف أسنان", doctor: "د. خالد المطيري", status: "مؤكد", tone: "bg-[#dcecf5] text-[#22617d]" },
  { id: 3, time: "١٠:٠٠", name: "ريم القحطاني", initials: "رق", service: "متابعة تقويم", doctor: "د. خالد المطيري", status: "بانتظار التأكيد", tone: "bg-[#fff0d8] text-[#9a6513]" },
  { id: 4, time: "١٠:٣٠", name: "عبدالله السالم", initials: "اس", service: "كشف عام", doctor: "د. أحمد الشمري", status: "مؤكد", tone: "bg-[#dcecf5] text-[#22617d]" },
  { id: 5, time: "١١:٠٠", name: "جود الزهراني", initials: "جز", service: "استشارة تغذية", doctor: "د. نورة الحربي", status: "مؤكد", tone: "bg-[#dcecf5] text-[#22617d]" },
];
const alerts = [
  { id: 1, icon: "↗", title: "تأكيد موعد مطلوب", detail: "ريم القحطاني · اليوم ١٠:٠٠", action: "إرسال تذكير", tone: "amber" },
  { id: 2, icon: "◌", title: "متابعة لم تتم", detail: "خالد العبدالله · منذ ٣ أيام", action: "فتح المتابعة", tone: "coral" },
  { id: 3, icon: "!", title: "موعد فائت", detail: "نوف الغامدي · أمس ١٦:٣٠", action: "التواصل الآن", tone: "blue" },
];

function StatCard({ label, value, meta, accent, icon }: { label: string; value: string; meta: string; accent: string; icon: React.ReactNode }) {
  return <div className="animate-enter soft-shadow rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] p-4 transition hover:-translate-y-0.5 hover:shadow-[var(--shadow-md)]">
    <div className="mb-4 flex items-start justify-between"><span className={`grid size-9 place-items-center rounded-xl ${accent}`}>{icon}</span><MoreHorizontal size={17} className="text-[hsl(var(--muted-foreground)/.55)]" /></div>
    <p className="text-[12px] font-semibold text-[hsl(var(--muted-foreground))]">{label}</p><div className="mt-1 flex items-baseline gap-2"><strong className="text-[27px] tracking-tight">{value}</strong><span className="text-[11px] font-semibold text-[hsl(var(--primary))]">{meta}</span></div>
  </div>;
}

export default function Dashboard() {
  const [selected, setSelected] = useState<Appointment | null>(null);
  const [booking, setBooking] = useState(false);
  const [sent, setSent] = useState<number[]>([]);
  const { language } = usePreferences();
  const en = language === "en";
  return <section className="mx-auto max-w-[1450px]">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold text-[hsl(var(--primary))]"><span className="size-2 rounded-full bg-[hsl(var(--primary))]" /> {en ? "Tuesday · A calm, organized day" : "الثلاثاء · يوم هادئ ومنظم"}</div><h1 className="text-[27px] font-extrabold tracking-tight md:text-[31px]">{en ? "Today's overview" : "صورة اليوم"} <span className="text-[hsl(var(--muted-foreground))]">/ {en ? "Operations" : "التشغيل"}</span></h1><p className="mt-1 text-[13px] text-[hsl(var(--muted-foreground))]">{en ? "Everything that needs your attention, in one place." : "كل ما يحتاج انتباهك، في مكان واحد."}</p></div><button data-testid="button-new-booking-dashboard" onClick={() => setBooking(true)} className="flex items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-4 py-2.5 text-[12px] font-bold text-white shadow-[0_6px_16px_hsl(var(--primary)/.18)] transition hover:-translate-y-0.5 hover:bg-[hsl(var(--primary)/.9)] active:translate-y-0"><Plus size={17} /> {en ? "New appointment" : "حجز موعد جديد"}</button></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><StatCard label={en ? "Today's appointments" : "مواعيد اليوم"} value="٢٤" meta={en ? "+3 from yesterday" : "+٣ عن أمس"} accent="bg-[#d9f0e8] text-[#176b58]" icon={<CalendarPlus size={18} />} /><StatCard label={en ? "Waiting now" : "في الانتظار"} value="٠٣" meta={en ? "Now" : "الآن"} accent="bg-[#fff0d8] text-[#9a6513]" icon={<Clock3 size={18} />} /><StatCard label={en ? "Attendance rate" : "معدل الحضور"} value="٨٧٪" meta={en ? "+4.2% this month" : "+٤٫٢٪ هذا الشهر"} accent="bg-[#dcecf5] text-[#22617d]" icon={<Check size={18} />} /><StatCard label={en ? "Assistant replies" : "ردود المساعد"} value="١٨" meta={en ? "Today" : "اليوم"} accent="bg-[#e8e1f4] text-[#65518b]" icon={<PhoneCall size={18} />} /></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(310px,.9fr)]">
      <div className="min-w-0 rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] shadow-[var(--shadow-sm)]">
         <div className="flex items-center justify-between border-b border-[hsl(var(--border)/.65)] px-5 py-4"><div><h2 className="text-[15px] font-extrabold">{en ? "Today's schedule" : "جدول اليوم"}</h2><p className="mt-0.5 text-[11px] text-[hsl(var(--muted-foreground))]">{en ? "Tuesday, June 18 · 09:00 — 18:00" : "الثلاثاء، ١٨ يونيو · ٠٩:٠٠ — ١٨:٠٠"}</p></div><Link href="/appointments" data-testid="link-view-all-appointments" className="flex items-center gap-1 text-[11px] font-bold text-[hsl(var(--primary))] hover:gap-2">{en ? "View all" : "عرض الكل"} <ChevronLeft size={14} /></Link></div>
        <div className="divide-y divide-[hsl(var(--border)/.55)]">{appointments.map((apt, i) => <button key={apt.id} data-testid={`row-appointment-${apt.id}`} onClick={() => setSelected(apt)} className={`animate-enter stagger-${Math.min(i + 1, 3)} flex w-full items-center gap-3 px-5 py-3.5 text-right transition hover:bg-[hsl(var(--muted)/.55)] ${selected?.id === apt.id ? "bg-[hsl(var(--primary)/.05)]" : ""}`}><span className="w-[47px] text-[12px] font-bold text-[hsl(var(--muted-foreground))] mono">{apt.time}</span><span className={`grid size-9 shrink-0 place-items-center rounded-full text-[11px] font-bold ${apt.tone}`}>{apt.initials}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[12px]">{apt.name}</strong><span className="block truncate text-[10px] text-[hsl(var(--muted-foreground))]">{apt.service} · {apt.doctor}</span></span><span className={`hidden rounded-md px-2 py-1 text-[10px] font-bold sm:block ${apt.status === "وصل" ? "bg-[#d9f0e8] text-[#176b58]" : apt.status === "بانتظار التأكيد" ? "bg-[#fff0d8] text-[#9a6513]" : apt.status === "ملغي" ? "bg-[#f9dfdc] text-[#a64036]" : "bg-[#dcecf5] text-[#22617d]"}`}>{apt.status}</span><ChevronLeft size={15} className="text-[hsl(var(--muted-foreground)/.45)]" /></button>)}</div>
        <div className="flex items-center justify-center border-t border-[hsl(var(--border)/.6)] py-3"><Link href="/calendar" data-testid="link-open-calendar" className="text-[11px] font-bold text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--primary))]">فتح الجدول الكامل</Link></div>
      </div>
      <div className="rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] shadow-[var(--shadow-sm)]"><div className="flex items-center justify-between border-b border-[hsl(var(--border)/.65)] px-5 py-4"><div><h2 className="text-[15px] font-extrabold">يحتاج انتباهك</h2><p className="mt-0.5 text-[11px] text-[hsl(var(--muted-foreground))]">٣ عناصر تنتظر قرارك</p></div><span className="grid size-7 place-items-center rounded-lg bg-[#fff0d8] text-xs font-bold text-[#9a6513]">٣</span></div><div className="space-y-2.5 p-3">{alerts.map(item => <div key={item.id} className={`rounded-xl border p-3 ${item.tone === "amber" ? "border-[#f2dfb9] bg-[#fffaf0]" : item.tone === "coral" ? "border-[#f0d1cd] bg-[#fff8f7]" : "border-[#d3e4ef] bg-[#f5fbfe]"}`}><div className="flex gap-3"><span className={`grid size-8 shrink-0 place-items-center rounded-lg text-sm font-bold ${item.tone === "amber" ? "bg-[#f8e7bd] text-[#986311]" : item.tone === "coral" ? "bg-[#f5d8d4] text-[#ad4338]" : "bg-[#dbeaf3] text-[#28647e]"}`}>{item.icon}</span><div className="min-w-0 flex-1"><strong className="block text-[11px]">{item.title}</strong><p className="mt-0.5 truncate text-[10px] text-[hsl(var(--muted-foreground))]">{item.detail}</p><button data-testid={`button-alert-${item.id}`} onClick={() => setSent(x => x.includes(item.id) ? x : [...x, item.id])} className="mt-2 text-[10px] font-extrabold text-[hsl(var(--primary))] hover:underline">{sent.includes(item.id) ? "تم الإرسال ✓" : item.action}</button></div></div></div>)}</div><Link href="/follow-ups" data-testid="link-open-followups" className="mx-4 mb-4 flex items-center justify-between rounded-lg bg-[hsl(var(--muted)/.7)] px-3 py-2.5 text-[10px] font-bold text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--primary))]">فتح قائمة المتابعات <ArrowUpLeft size={14} /></Link></div>
    </div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] p-5 shadow-[var(--shadow-sm)]"><div className="mb-4 flex items-center justify-between"><h2 className="text-[15px] font-extrabold">إيقاع العيادة</h2><span className="text-[10px] text-[hsl(var(--muted-foreground))]">آخر ٧ أيام</span></div><div className="flex h-[110px] items-end gap-3 px-2">{[52, 74, 60, 87, 69, 94, 80].map((height, i) => <div key={i} className="group flex flex-1 flex-col items-center gap-2"><div className="relative w-full rounded-t-lg bg-[hsl(var(--secondary))] transition-all group-hover:bg-[hsl(var(--primary)/.7)]" style={{ height: `${height}%` }}><span className="absolute -top-5 left-1/2 -translate-x-1/2 text-[9px] font-bold text-[hsl(var(--muted-foreground))] opacity-0 transition group-hover:opacity-100">{[17, 22, 18, 26, 21, 29, 24][i]}</span></div><span className="text-[9px] text-[hsl(var(--muted-foreground))]">{["أحد", "اثن", "ثلا", "أرب", "خمي", "جمع", "سبت"][i]}</span></div>)}</div></div><div className="dot-grid rounded-2xl border border-[hsl(var(--primary)/.16)] bg-[hsl(var(--primary)/.04)] p-5"><div className="mb-3 flex items-center gap-2 text-[hsl(var(--primary))]"><span className="grid size-8 place-items-center rounded-lg bg-[hsl(var(--primary)/.13)]"><PhoneCall size={16} /></span><span className="text-[11px] font-bold">ملاحظة من ClinicOS</span></div><p className="max-w-sm text-[14px] font-bold leading-7">الساعة ١١:٣٠ هي أهدأ فترة اليوم — وقت مناسب لمراجعة قائمة المتابعة.</p><Link href="/follow-ups" data-testid="link-note-followups" className="mt-3 inline-flex items-center gap-1 text-[11px] font-bold text-[hsl(var(--primary))]">اذهب للمتابعات <ArrowUpLeft size={14} /></Link></div></div>
    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#102c32]/35 p-0 sm:items-center sm:p-4" onClick={() => setSelected(null)}><div dir="rtl" onClick={e => e.stopPropagation()} className="w-full max-w-md rounded-t-3xl bg-[hsl(var(--card))] p-6 shadow-[var(--shadow-xl)] sm:rounded-3xl"><div className="mb-5 flex items-start justify-between"><div><span className="text-[11px] font-bold text-[hsl(var(--primary))]">تفاصيل الموعد</span><h2 className="mt-1 text-xl font-extrabold">{selected.name}</h2></div><button aria-label="إغلاق التفاصيل" data-testid="button-close-appointment-details" onClick={() => setSelected(null)} className="rounded-lg p-2 text-[hsl(var(--muted-foreground))] hover:bg-[hsl(var(--muted))]"><X size={18} /></button></div><div className="space-y-3 rounded-2xl bg-[hsl(var(--muted)/.65)] p-4 text-[12px]"><div className="flex justify-between"><span className="text-[hsl(var(--muted-foreground))]">الوقت</span><strong>{selected.time} · الثلاثاء ١٨ يونيو</strong></div><div className="flex justify-between"><span className="text-[hsl(var(--muted-foreground))]">الخدمة</span><strong>{selected.service}</strong></div><div className="flex justify-between"><span className="text-[hsl(var(--muted-foreground))]">الطبيب</span><strong>{selected.doctor}</strong></div></div><div className="mt-5 flex gap-2"><button data-testid="button-mark-arrived" onClick={() => setSelected(null)} className="flex-1 rounded-xl bg-[hsl(var(--primary))] py-2.5 text-xs font-bold text-white">تسجيل الوصول</button><button data-testid="button-cancel-appointment" onClick={() => setSelected(null)} className="rounded-xl border border-[hsl(var(--border))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--destructive))]">إلغاء الموعد</button></div></div></div>}
    {booking && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#102c32]/35 p-4"><div dir="rtl" className="w-full max-w-md rounded-3xl bg-[hsl(var(--card))] p-6 shadow-[var(--shadow-xl)]"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-extrabold">حجز موعد جديد</h2><button aria-label="إغلاق الحجز" data-testid="button-close-booking" onClick={() => setBooking(false)}><X size={18} /></button></div><div className="space-y-3"><label className="block text-xs font-bold">اسم المريض<input data-testid="input-booking-patient" className="mt-1.5 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2.5 text-xs outline-none focus:border-[hsl(var(--primary))]" placeholder="ابحث عن مريض أو أضف جديداً" /></label><label className="block text-xs font-bold">الخدمة<select data-testid="select-booking-service" className="mt-1.5 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2.5 text-xs"><option>استشارة جلدية</option><option>تنظيف أسنان</option><option>كشف عام</option></select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">التاريخ<input data-testid="input-booking-date" type="date" className="mt-1.5 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2.5 text-xs" /></label><label className="text-xs font-bold">الوقت<select data-testid="select-booking-time" className="mt-1.5 w-full rounded-xl border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 py-2.5 text-xs"><option>١٢:٠٠</option><option>١٢:٣٠</option><option>١٣:٠٠</option></select></label></div></div><button data-testid="button-confirm-booking" onClick={() => setBooking(false)} className="mt-5 w-full rounded-xl bg-[hsl(var(--primary))] py-3 text-xs font-bold text-white">تأكيد الحجز</button></div></div>}
  </section>;
}